import forms from "@tailwindcss/forms";

export default {
  content: ["./src/**/*.{html,ts}"],
  theme: {
    extend: {
      colors: {
        primary: "#e1fff1",
        "mint-accent": "#81F0CA",
        background: "#0f1512",
        "surface-elevated": "#1A1F21",
        "surface-cream": "#d3d3d3",
        "deep-carbon": "#0B0F10",
        "text-secondary": "#0f1512",
        "on-surface-variant": "#bccac2",
        "portal-tertiary-fixed-dim": "#c6c6c7",
        "portal-on-secondary": "#ffffff",
        "portal-outline": "#6d7a73",
        "portal-inverse-primary": "#5adcb3",
        "portal-primary-fixed-dim": "#5adcb3",
        "portal-surface-container-low": "#f2f4f6",
        "portal-surface-container-high": "#e6e8ea",
        "portal-on-primary-fixed-variant": "#00513d",
        "portal-primary-fixed": "#79f9ce",
        "portal-on-primary-container": "#00765b",
        "portal-on-tertiary-fixed-variant": "#454747",
        "portal-surface-container-highest": "#e0e3e5",
        "portal-primary": "#006c52",
        "portal-on-secondary-fixed": "#151d1c",
        "portal-secondary": "#58605f",
        "portal-on-primary-fixed": "#002117",
        "portal-surface-variant": "#e0e3e5",
        "portal-on-secondary-fixed-variant": "#404847",
        "portal-outline-variant": "#bccac2",
        "portal-inverse-surface": "#2d3133",
        "portal-surface-container-lowest": "#ffffff",
        "portal-surface": "#f7f9fb",
        "portal-on-surface": "#191c1e",
        "portal-error": "#ba1a1a",
        "portal-on-tertiary": "#ffffff",
        "portal-tertiary-fixed": "#e2e2e2",
        "portal-on-primary": "#ffffff",
        "portal-error-container": "#ffdad6",
        "portal-surface-tint": "#006c52",
        "portal-surface-dim": "#d8dadc",
        "portal-on-background": "#191c1e",
        "portal-surface-bright": "#f7f9fb",
        "portal-on-error-container": "#93000a",
        "portal-secondary-container": "#d9e1df",
        "portal-primary-container": "#7fffd4",
        "portal-surface-container": "#eceef0",
        "portal-tertiary-container": "#e8e8e8",
        "portal-tertiary": "#5d5f5f",
        "portal-background": "#f7f9fb",
        "portal-inverse-on-surface": "#eff1f3",
        "portal-on-error": "#ffffff",
        "portal-on-tertiary-container": "#666868",
        "portal-secondary-fixed-dim": "#c0c8c6",
        "portal-secondary-fixed": "#dce4e2",
        "portal-on-secondary-container": "#5c6463",
        "portal-on-surface-variant": "#3d4a44",
        "portal-on-tertiary-fixed": "#1a1c1c"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        xl: "0.75rem",
        full: "9999px",
        portal: "1rem",
        "portal-lg": "2rem",
        "portal-xl": "3rem"
      },
      spacing: {
        gutter: "32px",
        "margin-mobile": "24px",
        "container-max": "1440px",
        "section-gap": "160px",
        "margin-desktop": "80px",
        "portal-stack-sm": "8px",
        "portal-stack-md": "16px",
        "portal-stack-lg": "32px",
        "portal-section-padding": "120px",
        "portal-gutter": "24px",
        "portal-container-max": "1280px"
      },
      fontFamily: {
        "headline-lg": ["Bricolage Grotesque"],
        "headline-md": ["Bricolage Grotesque"],
        "display-xl": ["Bricolage Grotesque"],
        "body-lg": ["Hanken Grotesk"],
        "body-md": ["Hanken Grotesk"],
        "label-sm": ["JetBrains Mono"],
        "portal-headline-lg": ["Hanken Grotesk"],
        "portal-headline-xl": ["Hanken Grotesk"],
        "portal-headline-xl-mobile": ["Hanken Grotesk"],
        "portal-display-lg": ["Hanken Grotesk"],
        "portal-body-md": ["Hanken Grotesk"],
        "portal-body-lg": ["Hanken Grotesk"],
        "portal-button": ["Hanken Grotesk"],
        "portal-label-md": ["Hanken Grotesk"]
      },
      fontSize: {
        "display-xl": ["96px", { lineHeight: "100px", letterSpacing: "-0.04em", fontWeight: "800" }],
        "headline-lg": ["64px", { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "body-lg": ["20px", { lineHeight: "32px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "500" }],
        "portal-headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "700" }],
        "portal-headline-xl": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "portal-headline-xl-mobile": ["36px", { lineHeight: "1.2", fontWeight: "700" }],
        "portal-display-lg": ["72px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "800" }],
        "portal-body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "portal-body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "portal-button": ["13px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "700" }],
        "portal-label-md": ["14px", { lineHeight: "1.4", letterSpacing: "0.1em", fontWeight: "600" }]
      }
    }
  },
  corePlugins: { preflight: true },
  plugins: [forms]
};
