spring.application.name=Vetopia
server.port=8080


# Perfil activo: define la base de datos que usa la aplicación.
#   h2  -> base de datos H2 en archivo (application-h2.properties)
spring.profiles.active=h2


# URLS PARA VISUALIZAR (arrancar antes con: mvn spring-boot:run)
#   Landing institucional : http://localhost:8080/
#   Login                 : http://localhost:8080/login
#   Veterinario (listado) : http://localhost:8080/veterinario/mascotas
#   Veterinario (ficha)   : http://localhost:8080/veterinario/mascotas/ficha?id=2
#   Cliente (listado)     : http://localhost:8080/cliente/mascotas
#   Cliente (detalle)     : http://localhost:8080/cliente/mascotas/detalle?id=2


# Locale en español para el formato de fechas de Thymeleaf (#temporals)
spring.web.locale=es_CO
spring.web.locale-resolver=fixed

# Desactivar caché de plantillas durante el desarrollo
spring.thymeleaf.cache=false
